### ISSUE TITLE
Does not wotk with Hexo 4.0.0

### ISSUE THREAD

**Issue by steveww** [hexojs/hexo-filter-responsive-images#68] opened 2019-11-06 19:28 UTC
Any plans to upgrade this to work with Hexo 4.0.0?

The help image_version is not found.

**Comment by ertrzyiks** [comment] 2019-11-07 10:42
Thanks for reporting 👍 I will try to update it next week

**Comment by steveww** [comment] 2019-11-08 15:30
I've beaning looking at this and it's a more general malaise with Hexo 4.0. None of the filters are working e.g. <%- url_for('foo') %> throws a JS error url_for not found. Looks like there are serious issues with 4.0. I should never trust a dot zero release. Rolling back to 3.x

**Comment by SukkaW** [comment] 2019-11-08 15:36
@steveww Please open a issue at `hexojs/hexo` [here](https://github.com/hexojs/hexo/issues) if you encounter some problems on Hexo 4.0. IMHO, there must be something wrong with your Node.js version or `node_modules`.

I will retain this issue opened since the unit-test for this plugin has not update to Hexo 4.0.0 yet.
I believe the unit-test will pass like a flying color even after @ertrzyiks update unit-test for Hexo@4:

https://github.com/hexojs/hexo-filter-responsive-images/blob/d70c616cbd161212746b4e0081202cd50ba33a62/package.json#L34

**Comment by ertrzyiks** [comment] 2019-11-15 19:41
It's merged to master branch and all the specs are green. I'm struggling updating my blog to hexo4, so until I can test it properly I won't publish a new version.

**Comment by SukkaW** [comment] 2019-11-15 20:27
@ertrzyiks If you have encountered some problem when updating to Hexo@4, you can create a discussion at GitHub Org Team page. Then we might be able to find out what we had missed in Hexo 4.0.0 Release notes, and to prevent other users from encountering them.

**Comment by ertrzyiks** [comment] 2019-11-16 08:32
@SukkaW the problems I had were not related to Hexo update directly, I had issues installing binary dependencies of `sharp` (it complained about wrong python/libvis version). I made it work and confirmed this plugin works with Hexo 4 with no other tweaks than in package.json.

1.5.0 is out  :tada:

**Closed by ertrzyiks** 2019-11-16 08:32 UTC
